### ISSUE TITLE
Issues with notion and dndbeyond

### ISSUE THREAD

**Issue by kirenesnah** [ardittristan/VTTInlineWebviewer#11]
Hi Ardittristan,
I'm having an issue where neither of these webpages are loading correctly. I've installed the extension as you've said in your readme, but maybe I'm missing something. I've attached images as to what is happening and I'm hoping you can shed some light on what's going on.
![FoundryVTT_sOBnZ2jSI4](https://user-images.githubusercontent.com/45153491/114075276-018ef200-986b-11eb-9a68-fc5b3b9cd02a.jpg)
![FuWFo9DotE](https://user-images.githubusercontent.com/45153491/114075300-0653a600-986b-11eb-9d39-040db758f5e9.jpg)

**Comment by ardittristan** [comment]
hi there, the extension doesn't work directly inside the foundry.exe application. did you try via http://localhost:30000 ?

**Comment by kirenesnah** [comment]
Yes I tested it on my wife's computer while on the same LAN. I am also running the stable 0.7.X version of Foundry which it seems isn't supported? Would that possibly be the issue?

**Comment by ardittristan** [comment]
I've been working on it and I've found a solution to it in the extension. it shouldn't require any update to the foundry module (except for some documentation updates) so you can keep using your current version. (only change last update was making it 0.8 compatible which made it 0.7 incompatible)

**Comment by ardittristan** [comment]
It should be fixed with the latest extension update. Could you test? (logging in inside a webview requires a devtools window to be open, if already logged in it should work automatically)

**Comment by kirenesnah** [comment]
Now I'm unable to even install the module. It says that I have to have a 0.8.X version of Foundry to install. I've tried uninstalling and reinstalling Foundry and I've tried using older manifest URL's and it keeps blocking me. I'm unsure how to proceed.

**Comment by kirenesnah** [comment]
![FoundryVTT_dYo9GudvxZ](https://user-images.githubusercontent.com/45153491/114289334-a9a7e500-9a3c-11eb-872e-d7b410c1411d.png)

**Comment by ardittristan** [comment]
I made the module compatible with 0.7 again, can you retry? (and also make sure you updated the browser extension)

**Comment by kirenesnah** [comment]
![chrome_oAscwiNW4t](https://user-images.githubusercontent.com/45153491/114316232-495e8500-9ac8-11eb-80c2-8c8aa6eb2e68.png)
This is the error that I get with the 1.1.0 Chrome Extension. I'm still getting the same issue as before with Mismatch errors.

**Comment by kirenesnah** [comment]
![wJVpf4NC4G](https://user-images.githubusercontent.com/45153491/114316302-92aed480-9ac8-11eb-8de9-c8300ad6b08a.jpg)
Left is without compatibility Mode. Right is with it on. Both are the Notion page.

**Comment by ardittristan** [comment]
> ![wJVpf4NC4G](https://user-images.githubusercontent.com/45153491/114316302-92aed480-9ac8-11eb-8de9-c8300ad6b08a.jpg)
> Left is without compatibility Mode. Right is with it on. Both are the Notion page.

This is inside foundry.exe though, it doesn't work inside foundry.exe
it should work inside the browser where the extension is installed at http://localhost:30000/
the extension error is on a different page than the foundry instance, and shouldn't affect the extension. (I will push a fix hiding the error)

did you try it at http://localhost:30000/ in the browser where the extension is installed?

**Comment by kirenesnah** [comment]
So sorry. It works now. Sorry about that! Thanks for all the help I appreciate it.

**Comment by ardittristan** [comment]
Great!
No problem, this made me implement a fix for the login issues
